### ISSUE TITLE
感谢大佬🙏 请问后续会考虑支持GPT-4、GPT4-Turbo吗？

### ISSUE THREAD

**Issue by suliveevil** [fatwang2/search2ai#1]
<img width="1259" alt="image" src="https://github.com/fatwang2/search2ai/assets/35763237/ebb3a4ef-0dba-4427-9930-3b2a8da4b998">

**Comment by fatwang2** [comment]
这些模型都支持，只要模型本身支持function calling就可以用
[image: image.png]

**Comment by fatwang2** [comment]
![image](https://github.com/fatwang2/search2ai/assets/134143178/a90791d9-0fd9-4a76-bf20-4174f2d21d26)

**Comment by fatwang2** [comment]
我自己在Opencat上试了下gpt-4，也是可以的

**Comment by suliveevil** [comment]
感谢感谢，可能是我这里设置、网络的问题，刚开始没能联网。
<img width="980" alt="image" src="https://github.com/fatwang2/search2ai/assets/35763237/0b2ce4b0-acf2-49be-a823-e0982dc64958">

**Comment by fatwang2** [comment]
那你现在可以了吗
