### ISSUE TITLE
大佬请看这里bug反馈。

### ISSUE THREAD

**Issue by 1487879421888** [fatwang2/search2ai#10]
第一，我已经在cf里面实现了域名的绑定，如下：
![image](https://github.com/fatwang2/search2ai/assets/47622641/b7cf922a-fdd3-4410-a9f8-4bf32bede7a6)
![image](https://github.com/fatwang2/search2ai/assets/47622641/43ca6eb7-124e-4ce9-9ea6-2d1946477ca9)
最后
![image](https://github.com/fatwang2/search2ai/assets/47622641/63901027-6c7d-44f8-be0b-978a9720f811)
![image](https://github.com/fatwang2/search2ai/assets/47622641/d52310db-256e-445d-8a2b-6fff42280ac6)
在next里面一直显示：正在输出，如下
![image](https://github.com/fatwang2/search2ai/assets/47622641/186ed5e4-18e9-4a0b-b707-292ba7e7a785)

**Comment by fatwang2** [comment]
你是用的OpenAI还是Gemini，如果是Gemini链接需要拼接完整，类似于下面这样。如果是OpenAI也要参考Next要求来配置，看是否需要带v1
https://geminiapi.search2ai.online/v1/models/gemini-pro:generateContent

**Comment by chris-ss** [comment]
有没有可能是APIBASE链接后面多了一个/

**Comment by fatwang2** [comment]
看下效果，Next上我是测试过的，没问题

https://github.com/fatwang2/search2ai/assets/134143178/159794d0-e6e8-49af-9ae4-8f146e20471d
