### ISSUE TITLE
这个项目根本就是假开源

### ISSUE THREAD

**Issue by qkxie** [fatwang2/search2ai#16]
核心逻辑全部都写在了https://search.search2ai.one 这个接口里面。现在开源出来的东西就是一个壳而已。用户的所有请求、配置的ID全部都会传入这个接口里面来处理。

一旦https://search.search2ai.one 这个接口挂了。用户自己部署的服务就会挂。

而且用户自定义的各种access key全部会泄露给这个项目的作者。

**Comment by fatwang2** [comment]
1、我写了风险声明。2、接口就是搜索接口，这算啥核心逻辑。核心逻辑是 function calling
的部分。3、理论上你可以直接把这个接口换成你的搜索接口，一样能用。4、后面本身也有计划要支持
searxng，本来还想着也放进这个搜索接口里，有担心的话，我就直接放出来吧

qkxie ***@***.***>于2024年4月24日 周三10:51写道：

**Comment by martin-yin** [comment]
https://search.search2ai.one/ 就一聚合搜索嘛，你不放心自己写一下步就完事了。

**Comment by fatwang2** [comment]
没事，我回头把这部分也开放出来，让大家放心

Martin ***@***.***>于2024年4月24日 周三15:44写道：

**Comment by fatwang2** [comment]
已经开源搜索接口的代码，并去掉了风险告知，这个确实没人看
