### ISSUE TITLE
about search url

### ISSUE THREAD

**Issue by lucky9-cyou** [fatwang2/search2ai#2]
https://github.com/fatwang2/search2ai/blob/e32a6642247a19b9da7a2fff8962f9680e25835c/search2ai#L45C39-L45C67

这个链接可能需要改成自己的？

**Comment by arouraus** [comment]
Send personal private search key to third party service?

**Comment by fatwang2** [comment]
> https://github.com/fatwang2/search2ai/blob/e32a6642247a19b9da7a2fff8962f9680e25835c/search2ai#L45C39-L45C67
> 
> 这个链接可能需要改成自己的？

不需要呀，这个是搜索+爬取服务，你不用自己部署。你只需要用我的代理地址，或者自己部署整个worker

**Comment by fatwang2** [comment]
> Send personal private search key to third party service?

那个是我自己搭的搜索爬取服务，如果不放心的话，我后面可以把这部分也开源出来，想自己部署就自己部署

**Comment by lucky9-cyou** [comment]
> > Send personal private search key to third party service?
> 
> 那个是我自己搭的搜索爬取服务，如果不放心的话，我后面可以把这部分也开源出来，想自己部署就自己部署

感谢
