### ISSUE TITLE
function call失败

### ISSUE THREAD

**Issue by yxmnjxzx** [fatwang2/search2ai#20]
cf搭建的互联网搜索，0.2.5后，function call网络搜索的数据获取不到，同样的在search2all中SERPER工作正常，测试了SERPAPI和bing均失败，api调用测试显示function call的q可以发出，网络数据读取失败

**Comment by fatwang2** [comment]
你更新到最新版试试，另外我没有search2all，你指的是哪个？

**Comment by yxmnjxzx** [comment]
是search4all，已更新最新版亦是无效

**Comment by fatwang2** [comment]
发一下你配置的变量吧

yxmnjxzx ***@***.***>于2024年4月27日 周六08:10写道：
