### ISSUE TITLE
搜索返回的内容样式还需要优化

### ISSUE THREAD

**Issue by scomper** [fatwang2/search2ai#22]
搜索返回的内容样式还需要优化一下，显示上有点奇怪。
![CleanShot 2024-04-27 at 22 05 22@2x](https://github.com/fatwang2/search2ai/assets/13041847/f7ce930b-d99c-47f6-90a6-944276171e87)

配置的模型是 Groq llama3-8b-8192
Cloudflare Worker [search2groq.js](https://github.com/fatwang2/search2ai/blob/main/search2groq.js)

**Comment by fatwang2** [comment]
搜索返回的是json，具体显示样式是大模型和客户端来处理的

**Comment by scomper** [comment]
了解了，我修改了一下提示语“... If the search returns JSON format, extract the JSON format and present it in a more readable way.”好像问题解决了。😄
