### ISSUE TITLE
Usage guide

### ISSUE THREAD

**Issue by risos8200** [fatwang2/search2ai#23]
Hi, I am trying to use this api for function calling? 

I am encountering these issues: 
When  I using the deploy to Zeabur, it gives internal server error

I also tried using local deployment, it gives Authorization header is missing when I try to open the api address?

Can you share some instructions how to use the api for function calling in python?

**Comment by fatwang2** [comment]
You need to use this deployed interface just like you use the OpenAI API.
You need to pass in your own key

**Comment by risos8200** [comment]
Do you think you can share some example for such a function call? I have not worked with JS or APIs much, if you can do it will be highly appreciated. 
Context: I am trying to implement it in Llama index function calling in python

**Comment by fatwang2** [comment]
I think you misunderstood this project. If you have used OpenAI's API before, after deploying this project, your way of calling will be the same, just change the API base. But if it does not support function calling itself, it will not be effective

**Comment by fatwang2** [comment]
It doesn't matter what language you use, just replace apibase with the address you deployed to use it

**Comment by risos8200** [comment]
Yes, I tried using it, but couldn't get it working, hence the studying the code a bit and API usage before implementing.
Closing this issue for now, will reach out incase I have any further questions. Regardless, thanks a lot and great on this API

**Comment by fatwang2** [comment]
which LLMs do you use and how do you deploy?

**Comment by risos8200** [comment]
I usually use either OpenAI through api calls or local llms using ollama or llama.cpp.

**Comment by fatwang2** [comment]
do you have telegtam or WhatsApp, I will show you how to deploy it

Rishabh Chanana ***@***.***>于2024年5月3日 周五18:31写道：

**Comment by risos8200** [comment]
yes, I have telegram. I joined your channel too! I will message you there, thanks a lot!
