### ISSUE TITLE
units文件夹里的三个后端是什么

### ISSUE THREAD

**Issue by CXwudi** [fatwang2/search2ai#5]
我看见units文件夹里三个js文件负责向后端（比如说搜索引擎）发请求，但使用是你自己的后端，比如`https://search.search2ai.one`，请问这是个什么后端，是否安全？

**Comment by fatwang2** [comment]
这就是我部署的各种接口，这部分暂时不开源，理论上你也可以换成其他接口

CXwudi ***@***.***>于2024年2月27日 周二16:20写道：

**Comment by CXwudi** [comment]
那比如说我要用google search，把`https://crawer.search2ai.one/`直接换成google search的API URL是否可行

**Comment by fatwang2** [comment]
你发的这个不是搜索接口，是内容爬取接口。搜索接口是支持你通过环境变量配置不同的搜索服务，用自己的 key 的

CXwudi ***@***.***>于2024年2月27日 周二16:45写道：

**Comment by CXwudi** [comment]
抱歉，接口发错了，我的意思是把`https://search.search2ai.one`直接换成google search API URL是否可行，假设部署服务器就在北美

**Comment by fatwang2** [comment]
你说的有道理，三思之后再用吧

CXwudi ***@***.***>于2024年2月27日 周二16:57写道：

**Comment by fatwang2** [comment]
我把这个不明后端的代码商业化了，这就是我不开源的原因，感兴趣可以下单体验下，搜索聚合 API，应该找不到更便宜的了， https://search2ai.online/api

**Comment by CXwudi** [comment]
非常感谢你的回复，不过我只是有个小的建议就是下次可以在readme标明一下这些后端是什么，比如说像这个wewe-rss项目一样[在readme写个风险说明](https://github.com/cooderl/wewe-rss?tab=readme-ov-file#%E9%A3%8E%E9%99%A9%E5%A3%B0%E6%98%8E)

**Comment by fatwang2** [comment]
已经加上了，感谢提醒
