### ISSUE TITLE
在ChatGPT-next 中配置了geminiapi，出错

### ISSUE THREAD

**Issue by laye0619** [fatwang2/search2ai#9]
终端地址：https://geminiapi.search2ai.online
<img width="993" alt="Screenshot 2024-04-07 at 14 38 38" src="https://github.com/fatwang2/search2ai/assets/9484313/cb347d99-0553-45b9-bcb5-d2d9c6df0ade">

对话：搜索abc

得到：
{
  "error": true,
  "message": "Request failed"
}

**Comment by fatwang2** [comment]
next 里配置，apibase 需要填完整的，你把后面的也拼上

**Comment by laye0619** [comment]
抱歉没太明白，我是想同时实现openai和gemini的搜索功能，我已经在环境变量里面BASE_URL配置成了https://api.search2ai.online，chatgpt使用正常。我现在想同时实现openai和gemini的搜索，那么gemini应该在哪里配置呢？

**Comment by laye0619** [comment]
> 抱歉没太明白，我是想同时实现openai和gemini的搜索功能，我已经在环境变量里面BASE_URL配置成了[https://api.search2ai.online，chatgpt使用正常。我现在想同时实现openai和gemini的搜索，那么gemini应该在哪里配置呢？](https://api.search2ai.online%EF%BC%8Cchatgpt%E4%BD%BF%E7%94%A8%E6%AD%A3%E5%B8%B8%E3%80%82%E6%88%91%E7%8E%B0%E5%9C%A8%E6%83%B3%E5%90%8C%E6%97%B6%E5%AE%9E%E7%8E%B0openai%E5%92%8Cgemini%E7%9A%84%E6%90%9C%E7%B4%A2%EF%BC%8C%E9%82%A3%E4%B9%88gemini%E5%BA%94%E8%AF%A5%E5%9C%A8%E5%93%AA%E9%87%8C%E9%85%8D%E7%BD%AE%E5%91%A2%EF%BC%9F)

环境变量中有一个GOOGLE_URL，我是在这里配置成https://geminiapi.search2ai.online/ 吗？您提到的拼接是要拼接什么？

**Comment by fatwang2** [comment]
1. 你如果用我的地址，拼接之后是这样的https://geminiapi.search2ai.online/v1/models/gemini-pro:generateContent，这个是Next客户端的问题，其他客户端就只需要https://geminiapi.search2ai.online，如果你是自己部署的，就替换我这个地址即可
2. 同时实现OpenAI和Gemini是啥意思，我没懂，每次肯定只能走一个大模型呀

**Comment by chunzha1** [comment]
尝试了https://chatgemini.search2ai.online/v1/models/gemini-pro:streamGenerateContent 和 https://chatgemini.search2ai.online 都没有成功，请问是否不支持了？

**Comment by fatwang2** [comment]
是支持的，我自己也在用，Gemini，你 api 版本那个字段换成 v1beta

**Comment by fatwang2** [comment]
还是用我提供的这个链接，是改 API 版本那个字段

**Comment by chunzha1** [comment]
https://geminiapi.search2ai.online/v1/models/gemini-pro:generateContent 尝试了这个，好像还是不行；这个对网络有要求吗？目前是HK的ip，不用设置endpoint是可以正常使用Gemini.

**Comment by fatwang2** [comment]
你理解错了，不是把链接里的v1 换掉，Next 不是有一个API 版本的字段，在那里填

**Comment by chunzha1** [comment]
> 你理解错了，不是把链接里的v1 换掉，Next 不是有一个API 版本的字段，在那里填

感谢回复~ 我是都改了v1beta，发现好像本地的就连不上，后面又尝试在线版的next chat可以连上了，可能是需要梯子；但是感觉查询效果不是很明显而且回复很短。
![image](https://github.com/fatwang2/search2ai/assets/125763492/5dfd839e-a3dd-420a-8ba9-061cd2f80184)

**Comment by fatwang2** [comment]
- 你把我那个链接前面的部分替换成你自己的域名，就可以用你自己的自定义域名
- 回复长短看 prompt

**Comment by fatwang2** [comment]
你看下我的录屏吧

https://github.com/fatwang2/search2ai/assets/134143178/4703a6a2-8d26-4c7b-aa4e-6f3b4aac7264
